UF3/2021/django/exempleVideo/cositas/cositas/urls.py
from django.contrib import admin
from django.urls import path, include, path

import pregunkane

urlpatterns = [
    path('admin/', admin.site.urls),
    #totes les urls que comencin per kane, li preguntarem al fitxer de urls de pregunkane
    path('kane/', include('pregunkane.urls')),
]

UF3/2021/django/exempleVideo/cositas/pregunkane/urls.py
from django.urls import path

from . import views

app_name = "pregunkane"
urlpatterns = [
    #si esta buit, ens envia a la vista index
    path('', views.index, name="index"),
    path('kane', views.index2, name="index2"),

    #a les URL puc posar parametres
    path('<int:question_id>/', views.detail, name='detail'),

    path('<int:question_id>/results/', views.results, name='results'),

    path('<int:question_id>/vote/', views.vote, name='vote'),
]

UF3/2021/django/exempleVideo/cositas/pregunkane/models.py
from django.db import models

# Create your models here.
from django.db import models

class Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=500)
    data = models.DateTimeField('data de la pregunta')

    def __str__(self):
        return self.texto_pregunta

class PossibleResposta(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE, related_name='respuestas')
    texto_respuesta = models.CharField(max_length=500)
    vots = models.IntegerField(default=0)

    def __str__(self):
        return self.texto_respuesta

UF3/2021/django/exempleVideo/cositas/pregunkane/views.py
from django.shortcuts import render
from django.http import Http404
# Create your views here.
from django.http import HttpResponse
from .models import *
from django.shortcuts import get_object_or_404, render


def index(request):
    #agafem amb NomClase.objects . tenim diversos metodes com get i order by. el - significa descendent
    ultimaspreguntas = Pregunta.objects.order_by('-data')[:5]
    #creo un diccionari context
    context = {'ultimaspreguntas': ultimaspreguntas}
    #render enviem el context com el compact
    return render(request, 'pregunkane/index.html', context)

def index2(request):
    return HttpResponse("Kane ya no tiene Kovid pero tiene pendiente")

def detail(request, question_id):
    try:
        pregunta = Pregunta.objects.get(pk=question_id)
    except Pregunta.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'pregunkane/detalle.html', {'pregunta': pregunta})

def results(request, question_id):
    response = "Mirando los resultados de la encuesta %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    pregunta = Pregunta.objects.get(pk=question_id)
    respuestaSeleccionada = pregunta.respuestas.get(pk=request.POST["choice"])
    respuestaSeleccionada.vots+=1
    respuestaSeleccionada.save()

UF3/2021/django/exempleVideo/cositas/pregunkane/templates/pregunkane/detalle.html
<form action="{% url 'pregunkane:vote' pregunta.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ pregunta.texto_pregunta }}</h1></legend>
    <!--error_message es una variable que es retorna automaticament a la template si hi ha hagut alguna excepcio -->
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <!--estem recorrent pregunta -->
    {% for posiblerespuesta in pregunta.respuestas.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ posiblerespuesta.id }}">
        <label for="choice{{ forloop.counter }}">{{ posiblerespuesta.texto_respuesta }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

UF3/2021/django/exempleVideo/cositas/pregunkane/templates/pregunkane/index.html
{% if ultimaspreguntas %}
    <ul>
    {% for preg in ultimaspreguntas %}
        <li><a href="/kane/{{ preg.id }}/">{{ preg.texto_pregunta }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay encuestas</p>
{% endif %}